stages:
  preprocess:
    cmd: python scripts/preprocess.py
    deps:
      - scripts/preprocess.py
      - data/raw/
    params:
      - preprocess.input_file
      - preprocess.target_file
      - preprocess.input_size
      - preprocess.test_split
      - preprocess.output_dir
    outs:
      - data/processed/processed_data.pt

  train:
    cmd: python scripts/train.py
    deps:
      - scripts/train.py
      - data/processed/processed_data.pt
    params:
      - train.name
      - train.batch_size
      - train.epochs
      - train.train_mode
    outs:
      - models/checkpoints


  export:
    cmd: python scripts/export.py
    deps:
      - scripts/export.py
      - models/checkpoints/
    params:
      - preprocess.input_size
      - train.name
      - train.train_mode
    outs:
      - models/exports

