stages:
  preprocess:
    cmd: python source/preprocess.py
    deps:
    - source/preprocess.py
    - data/raw/
    params:
    - preprocess.input_file
    - preprocess.target_file
    - preprocess.input_size
    - preprocess.test_split
    - preprocess.output_dir
    outs:
    - data/processed/
  train:
    cmd: python source/train.py
    deps:
    - source/train.py
    - data/processed/
    params:
    - train.name
    - train.batch_size
    - train.epochs
    - train.train_mode
    outs:
    - models/checkpoints/
    - dvclive/
    - tensorboard/
  export:
    cmd: python source/export.py
    deps:
    - source/export.py
    - models/checkpoints/
    params:
    - preprocess.input_size
    - train.name
    - train.train_mode
    outs:
    - models/exports/
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step


